name: Terraform Plan and Apply
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Terraform Apply
    environment: lab
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_S3: ${{ secrets.S3_ENDPOINT }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      TF_VAR_SIMPLELOGIN_ANONYMOUS_DOMAIN: ${{ vars.TF_VAR_SIMPLELOGIN_ANONYMOUS_DOMAIN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: AWS Assume Role
        id: assume_role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          role-session-name: ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -backend-config="bucket=${{ vars.STATE_BUCKET_NAME }}"
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
