name: Terraform Plan and Apply
on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Terraform Apply
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init \
            -backend-config="access_key=${{ secrets.S3_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.S3_SECRET_ACCESS_KEY }}" \
            -backend-config="bucket=${{ env.STATE_BUCKET_NAME }}" \
            -backend-config="endpoints={ s3 = \"${{ secrets.S3_ENDPOINT }}\" }"
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
