name: Terraform Plan and Apply
on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Terraform Apply
    environment: lab
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ secrets.S3_ENDPOINT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Terraform Init
        run: terraform init -chdir=terraform
      - name: Terraform Plan
        run: terraform plan -chdir=terraform -out=tfplan
      - name: Terraform Apply
        run: terraform apply -chdir=terraform -auto-approve tfplan
